### ISSUE TITLE
Can't access SD card on Android 6

### ISSUE THREAD

**Issue by ichaushev** [matthewn4444/onscripter-plus-android#21]
I placed the "ons" directory containing a VN on my SD card. There is no way to access and select this directory from the app on my Android 6 phone. I can only see the phone's internal storage from the app. If I put the VN on the internal storage, loading it works successfully.

I've had to explicitly grant SD card access to several apps (such as file managers) before I could read the full SD card file tree ([following this process](https://metactrl.com/docs/sdcard-on-lollipop/)) but I can't find a way to invoke this in ONScripter Plus. But this may be unnecessary.

After tapping the button which is supposed to switch to the SD card "/storage/emulated/0" and internal "/mnt/sdcard", it remains in internal storage because "/storage/emulated/0" points to it as well. I'm pretty sure the SD card on my phone is at "/storage/emulated/1". Could this issue be fixed? Thanks!

**Comment by matthewn4444** [comment]
There is no way in this app right now. I am currently writing a new version of this app from scratch which fixes it but will not live on this repository. The only way for now is to root your phone to enable write to sdcard (or wait for my new version). In any case, I added support for this on the engine https://github.com/matthewn4444/onscripter-engine-android/commit/73c8e4a885f919a0f087f9eb74a415490d89c0a2
