### ISSUE TITLE
PNG alpha and positioning

### ISSUE THREAD

**Issue by Dimoks** [matthewn4444/onscripter-plus-android#23]
"image\word\day_01.**_png_**" and "image\word\park_01a.**_png_**"
![day_01](https://user-images.githubusercontent.com/3314441/35240025-37c02482-ffc3-11e7-91ef-104e4455ec4f.png)
![park_01a](https://user-images.githubusercontent.com/3314441/35240006-25885eb0-ffc3-11e7-8327-827761df706b.png)
In “Tsukihime Russian Demo”.
```
mov $phasebg,"image\bg\bg_06a.jpg"
mov $phasetitle_a,":a;image\word\PARK_01A.PNG"
mov $phasetitle_b,":a;image\word\day_01.png"
gosub *right_phase
```
```
*right_phase
setwindow 18,18, 36,21, 17,17, 0, 4, 22, 1, 1, #ffffff, 0, 0, 639, 479
windoweffect 1
;カーソルの表示を行わない
setcursor 0,":c;icon\0.bmp",0,0
setcursor 1,":c;icon\0.bmp",0,0
;<右カーテン(速)>
bg $phasebg,%type_rcartain_fst
;<左カーテン(速)>
ld r,$phasetitle_a,%type_lcartain_fst
lsp 15,$phasetitle_b,320,440,0
mov %flushcount,0
resettimer
waittimer 16
msp 15,0,0,16
inc %flushcount
print 1
if %flushcount<16 skip -5
\
csp -1
bg #000000,%type_crossfade_fst
setwindow 18,18, 36,21, 17,17, 0, 4, 22, 1, 1, #aaaaaa, 0, 0, 639, 479
windoweffect 10, 300
setcursor 0,":l/3,160,2;icon\cursor0.bmp",0,0
setcursor 1,":l/3,160,2;icon\cursor1.bmp",0,0
return
```
PC (ONSLaught):
![20180113t231030_0002904284](https://user-images.githubusercontent.com/3314441/35239102-8f0898da-ffc0-11e7-801f-b92b312c9ff4.jpg)
ONScripter Plus 1.2.4:
![screenshot_2018-01-23-00-38-44](https://user-images.githubusercontent.com/3314441/35239133-a7fea0be-ffc0-11e7-8fdb-a3a3a6511ab6.png)
With "image\word\day_01_j.**_jpg_**" and "image\word\park_01a_j.**_jpg_**"
![screenshot_2018-01-23-01-53-47](https://user-images.githubusercontent.com/3314441/35239199-ddd93622-ffc0-11e7-9eea-f1ad8817d36b.png)

**Comment by matthewn4444** [comment]
Moving engine bugs to engine.

https://github.com/matthewn4444/onscripter-engine-android/issues/1

Closing here, please follow the issues page on the engine repo
